audeering/audobject

- CHANGELOG.rst
- setup.cfg
The first try of publishing the package on PyPI [has failed](https://github.com/audeering/audobject/runs/2184612779?check_suite_focus=true) as usual ;)
This cleans up the package metadata in order to avoid this failure.
> Cleanup package metadata

- audobject/core/decorator.py
- tests/test_object.py
Closes https://github.com/audeering/audobject/issues/12
```python
import audobject.testing
__version__ = '1.0.0'
class Parent(audobject.Object):
@audobject.init_decorator(
hide=[            
'parent',
],
)
def __init__(
self,
parent: bool = False,
):
self.parent = parent
class Child(Parent):
@audobject.init_decorator(
hide=[
'child',            
],
)
def __init__(
self,
child: bool = False,
parent: bool = False,
):        
super().__init__(parent=parent)
self.child = child
c = Child()
print(c.to_yaml_s())
```
```
$__main__.Child==1.0.0: {}
```
> FIX: inherit borrow, hide, and resolvers

- audobject/__init__.py
- audobject/core/decorator.py
- audobject/core/define.py
- audobject/core/object.py
- audobject/core/parameter.py
- audobject/core/resolver.py
- audobject/core/utils.py
- docs/api.rst
- docs/usage.rst
- tests/test_resolver.py
This adds a feature - as simple as it sounds - I have been struggeling with for some time. It will be useful if a user wants to serialize objects that require input from external files (e.g. a file storing model weights etc.). If we would simply store the file path as it is, we get a YAML that is not be portable as it will not find the files once we move it to another location.
As a solution this adds `FilePathResolver` to properly save and recover files path arguments. Here's what it does:
1. when the object is serialized convert the original file path to a path relative to the output directory
2. when the object is re-instantiated expand the file path again with the current input directory
Example from the usage section:
> Serialize file paths

- audobject/__init__.py
- audobject/core/api.py
- audobject/core/object.py
- docs/api.rst
- docs/usage.rst
- tests/test_object.py
- tests/test_parameters.py
- tests/test_resolver.py
- tests/test_warnings.py
Closes #15 
Deprecates the static `audobject.Object.from_*()` methods (with version 1.0.0) and introduces `audobject.from_*()` instead.
> Module-level load functions

- audobject/core/define.py
- audobject/core/object.py
- audobject/core/utils.py
- setup.cfg
- tests/requirements.txt
- tests/test_install.py
- tests/test_object.py
Closes #36 
In case module and package name do not match the class key is now extended from `$<module>.<class>==version` to `$<package>:<module>.<class>==version`. This is handled by a new internal utility function `utils.create_class_key()`. The function `utils.split_class_key()`, which takes care of splitting the key, will return the module name as package name if no explicit package name is given.
> Store package name if it does not match module

- audobject/core/decorator.py
Seems there was a deprecation warning left over.
I couldn't find any part of the code that needs to be changed, so I just removed the warning.
> Remove deprecation warning from init_decorator()

- audobject/__init__.py
- audobject/core/decorator.py
- audobject/core/resolver.py
Removes deprecated `audobject.ValueResolver`.
It was also still mentioned in the documentation:
> Remove deprecated audobject.ValueResolver

- audobject/core/api.py
We forgot to remove the comment about `auto_install` that package and module have to match. It's no longer required.
> DOC: fix docstring of auto_install argument

- audobject/core/api.py
- setup.cfg
- tests/conftest.py
- tests/test_install.py
In our tests with `auto_install=True` we forgot to cover `to_yaml()`, which basically relies on `to_yaml_s()`, but unfortunately, we do not pass on the argument at the moment. This fixes the bug and extends the test to cover it.
> Fix: poperly pass on auto_install argument

- audobject/core/define.py
- audobject/core/dictionary.py
- audobject/core/object.py
- audobject/core/testing.py
- docs/usage.rst
- tests/test_dictionary.py
- tests/test_object.py
Fixes #50 
Instead of serializing all attributes to YAML, we only store the attributes that are actually passed as keyword arguments. Therefore, we pass `kwargs` to the constructor of the base class.
> Fix: properly serialize keyword arguments

- audobject/core/api.py
- audobject/core/utils.py
- tests/test_dictionary.py
- tests/test_object.py
Ensures that `Object.is_loaded_from_dict` is already set in `__init__()`.
```python
class MyObject(audobject.Object):
def __init__(
self,
):
print(self.is_loaded_from_dict)
obj = MyObject()
audobject.from_yaml_s(obj.to_yaml_s(include_version=False))
```
```
False
True
```
Before this fix it was printing `False` in both cases.
> Fix: set is_loaded_from_dict before calling __init__()

- .github/workflows/flake8.yml
- .github/workflows/test.yml
- .gitignore
- .pre-commit-config.yaml
- CONTRIBUTING.rst
- audobject/core/decorator.py
- audobject/core/utils.py
- setup.cfg
- tests/requirements.txt
- tests/test_warnings.py
This uses [pre-commit](https://pre-commit.com) instead of `pytest` to execute the `flake8` tests.
It also fixes a few flake8 issues and adds a coding convention section to CONTRIBUTING.
> TST: use pre-commit for flake8 checks

- audobject/core/object.py
Fix the referenced type of `audobject.Object.arguments` from method to attributes in all `to_dict()` methods.
> DOC: correct type of Object.arguments reference

- .github/workflows/doc.yml
- .github/workflows/test.yml
Split testing/building the documentation to extra GitHub Action, and expand the tests for all Python versions to all platforms.
> CI: add extra doc Action

- docs/requirements.txt
`jupter-sphinx` does no longer install this package automatically, so we need to add it to the dependencies.
> DOC: add ipykernel as dependency

- audobject/__init__.py
`pkg_resources` is deprecated and since Python 3.8 we can use `importlib.metadata` to get the version of a package.
> Use importlib.metadata instead of pkg_resources

- tests/test_install.py
Switch to install the newest version of `audbackend` in the tests.
> TST: use audbackend>=1.0.1 for install test

- docs/requirements.txt
Set fixed `sphinx` version to speedup installation of doc packages (otherwise `pip` might start to download all available `sphinx` versions to see which one works with the other requirements).
> DOC: require sphinx==5.3.0

- audobject/core/resolver.py
Closes #21
Adds a discussion of the limitation of the `Function()` resolver to its docstring.
> DOC: discuss limits of resolver.Function

- docs/conf.py
Enables the before missing version number under the logo:
> DOC: show version under logo

- tests/test_install.py
Update the tests to handle the new `audbackend` 2.0.0 release.
> TST: update to audbackend>=2.0

- README.rst
The link was pointing to the license of `audfactory` before.
> DOC: fix license entry in README

- tests/conftest.py
- tests/test_install.py
For the test of a package that has a different module and install name, we replace `dohq-artifactory`, `artifactory` by `scikit-learn`, `sklearn`.
> TST: use sklearn instead of artifactory

- LICENSE
- docs/conf.py
Change the end of license year to `-present` and remove license year from documentation.
> Update license year
